name: lodt_hack
description: Leaders of digital transformation hack solution

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_chat_ui: ^1.6.8
  agora_rtc_engine: ^6.1.1+1
  speech_to_text: ^6.1.1
  excel: 2.1.0
  permission_handler: ^10.2.0

flutter:

  uses-material-design: true