name: lodt_hack
description: Leaders of digital transformation hack solution

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_chat_ui: ^1.6.8
  agora_rtc_engine: ^6.1.1+1
  speech_to_text: ^6.1.1
  excel: 2.1.0
  permission_handler: ^10.2.0
  grpc: ^3.1.0
  calendar_date_picker2: ^0.5.2
  google_fonts: ^4.0.0
  agora_uikit: ^1.3.3

  # to generate protobuf poggers run
  # dart pub global activate protoc_plugin
  # export PATH="$PATH:$HOME/.pub-cache/bin"
  # protoc --dart_out=grpc:lib/generated -Iprotos protos/app.proto google/protobuf/timestamp.proto google/protobuf/empty.proto
  # from the root of project
  protoc_plugin: ^20.0.1

flutter:

  uses-material-design: true